// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pingPong.proto

package com.niket.javaspringgrpc.proto_gen.ping_pong;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response = 2;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 2;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
